version: '3'
services:
        mysql-db:
                image: mysql:5.7
                container_name: mysql_app_cont
                environment:
                        - MYSQL_ROOT_PASSWORD=Raman
                        - MYSQL_DATABASE=mydb
                        - MYSQL_USER=raman
                        - MYSQL_PASSWORD=raman
                volumes:
                        - db:/var/lib/mysql

        node-backend:
                 depends_on:
                         - mysql-db
                 image: ramanrupal/node-app:0.1
                 container_name: node_app_cont
                 environment:
                         # - MYSQL_HOSTNAME=mysql_app_cont
                         - MYSQL_HOSTNAME=mysql-db
                         - MYSQL_DATABASE=mydb
                         - MYSQL_USER=raman
                         - MYSQL_PASSWORD=raman

        angular-frontend:
                image: ramanrupal/angular-app:0.2
                container_name: angular_app_cont
                ports: 
                         - 80:80
                depends_on:
                        - mysql-db
                        - node-backend

volumes:
        db:


